#!/usr/bin/env bash

while true; do
    read -e -p "pipe-flow $ " line || exit

    ./build/input "$line"
    rewritten=$(echo "$line" | sed 's/|/| .\/build\/data-send |/g')
    ./build/data-print
    ./build/data-clear
    bash -c "$rewritten"
done